SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `product_sub_catalog` (`id`, `parent_product_code`, `product_code`, `product_name`, `product_description`, `price`, `is_active`, `display_order`, `created_at`) VALUES ('c1a21827-43a2-4f20-8fca-c44942ed44ec', 'PROD_004', 'PG_SUB_001', 'Checkout Page', 'Standard payment gateway checkout integration for your website or app', NULL, 1, 1, '2026-04-15 12:08:46') ON DUPLICATE KEY UPDATE `parent_product_code`=VALUES(`parent_product_code`), `product_code`=VALUES(`product_code`), `product_name`=VALUES(`product_name`), `product_description`=VALUES(`product_description`), `price`=VALUES(`price`), `is_active`=VALUES(`is_active`), `display_order`=VALUES(`display_order`), `created_at`=VALUES(`created_at`);
INSERT INTO `product_sub_catalog` (`id`, `parent_product_code`, `product_code`, `product_name`, `product_description`, `price`, `is_active`, `display_order`, `created_at`) VALUES ('3d858504-b328-4476-b82d-b65b835c84c1', 'PROD_004', 'PG_SUB_002', 'Pay By Link', 'Create and share one-time payment links via SMS, WhatsApp or Email', NULL, 1, 2, '2026-04-15 12:08:46') ON DUPLICATE KEY UPDATE `parent_product_code`=VALUES(`parent_product_code`), `product_code`=VALUES(`product_code`), `product_name`=VALUES(`product_name`), `product_description`=VALUES(`product_description`), `price`=VALUES(`price`), `is_active`=VALUES(`is_active`), `display_order`=VALUES(`display_order`), `created_at`=VALUES(`created_at`);
INSERT INTO `product_sub_catalog` (`id`, `parent_product_code`, `product_code`, `product_name`, `product_description`, `price`, `is_active`, `display_order`, `created_at`) VALUES ('9f10686a-61da-40c7-b7ed-65678e4cd2db', 'PROD_004', 'PG_SUB_003', 'Easy Collect', 'Bulk payment link generation with auto reminders and outbound calling', NULL, 1, 3, '2026-04-15 12:08:46') ON DUPLICATE KEY UPDATE `parent_product_code`=VALUES(`parent_product_code`), `product_code`=VALUES(`product_code`), `product_name`=VALUES(`product_name`), `product_description`=VALUES(`product_description`), `price`=VALUES(`price`), `is_active`=VALUES(`is_active`), `display_order`=VALUES(`display_order`), `created_at`=VALUES(`created_at`);
INSERT INTO `product_sub_catalog` (`id`, `parent_product_code`, `product_code`, `product_name`, `product_description`, `price`, `is_active`, `display_order`, `created_at`) VALUES ('181bd9ea-5773-4097-9f5f-b3d181d0f604', 'PROD_004', 'PG_SUB_004', 'Split Payment', 'Automatically split payment collections across multiple accounts — seller, agent, platform', NULL, 1, 4, '2026-04-15 12:08:46') ON DUPLICATE KEY UPDATE `parent_product_code`=VALUES(`parent_product_code`), `product_code`=VALUES(`product_code`), `product_name`=VALUES(`product_name`), `product_description`=VALUES(`product_description`), `price`=VALUES(`price`), `is_active`=VALUES(`is_active`), `display_order`=VALUES(`display_order`), `created_at`=VALUES(`created_at`);
INSERT INTO `product_sub_catalog` (`id`, `parent_product_code`, `product_code`, `product_name`, `product_description`, `price`, `is_active`, `display_order`, `created_at`) VALUES ('3f929a50-4510-47f9-947b-ce5e8f54c1c4', 'PROD_004', 'PG_SUB_005', 'Discount Coupons', 'Create and manage discount coupon codes applied at checkout', NULL, 1, 5, '2026-04-15 12:08:46') ON DUPLICATE KEY UPDATE `parent_product_code`=VALUES(`parent_product_code`), `product_code`=VALUES(`product_code`), `product_name`=VALUES(`product_name`), `product_description`=VALUES(`product_description`), `price`=VALUES(`price`), `is_active`=VALUES(`is_active`), `display_order`=VALUES(`display_order`), `created_at`=VALUES(`created_at`);
INSERT INTO `product_sub_catalog` (`id`, `parent_product_code`, `product_code`, `product_name`, `product_description`, `price`, `is_active`, `display_order`, `created_at`) VALUES ('ed53c1c4-9e7b-4a96-98b3-be2d75b3fdf1', 'PROD_004', 'PG_SUB_006', 'UPI 2.0 AutoPay', 'Pre-authorize and auto-debit customer accounts via UPI mandate registration', NULL, 1, 6, '2026-04-15 12:08:46') ON DUPLICATE KEY UPDATE `parent_product_code`=VALUES(`parent_product_code`), `product_code`=VALUES(`product_code`), `product_name`=VALUES(`product_name`), `product_description`=VALUES(`product_description`), `price`=VALUES(`price`), `is_active`=VALUES(`is_active`), `display_order`=VALUES(`display_order`), `created_at`=VALUES(`created_at`);
INSERT INTO `product_sub_catalog` (`id`, `parent_product_code`, `product_code`, `product_name`, `product_description`, `price`, `is_active`, `display_order`, `created_at`) VALUES ('f4662977-584a-44b2-97ce-2b997f752fa4', 'PROD_004', 'PG_SUB_007', 'SmartPay', 'Fully customizable payment page with your own branding and URL', NULL, 1, 7, '2026-04-15 12:08:46') ON DUPLICATE KEY UPDATE `parent_product_code`=VALUES(`parent_product_code`), `product_code`=VALUES(`product_code`), `product_name`=VALUES(`product_name`), `product_description`=VALUES(`product_description`), `price`=VALUES(`price`), `is_active`=VALUES(`is_active`), `display_order`=VALUES(`display_order`), `created_at`=VALUES(`created_at`);
INSERT INTO `product_sub_catalog` (`id`, `parent_product_code`, `product_code`, `product_name`, `product_description`, `price`, `is_active`, `display_order`, `created_at`) VALUES ('4648d3b2-e6e7-4871-91ad-b50979c50a97', 'PROD_004', 'PG_SUB_008', 'Sub-merchant Management', 'Onboard and manage sub-merchants under your master merchant account', NULL, 1, 8, '2026-04-15 12:08:46') ON DUPLICATE KEY UPDATE `parent_product_code`=VALUES(`parent_product_code`), `product_code`=VALUES(`product_code`), `product_name`=VALUES(`product_name`), `product_description`=VALUES(`product_description`), `price`=VALUES(`price`), `is_active`=VALUES(`is_active`), `display_order`=VALUES(`display_order`), `created_at`=VALUES(`created_at`);

SET FOREIGN_KEY_CHECKS=1;